// <auto-generated />
using Back.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Back.Infrastructure.Database
{
    [DbContext(typeof(LogiTrackDbContext))]
    [Migration("20260607000001_AddFotoPerfilToUsuarios")]
    partial class AddFotoPerfilToUsuarios
    {
    }
}
