// <auto-generated />
using System;
using Back.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Back.Infrastructure.Database
{
    [DbContext(typeof(LogiTrackDbContext))]
    partial class LogiTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Back.Domain.Models.ConfiguracionOjoPatron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UmbralAlertness")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesOjoPatron", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.ConfiguracionTarifa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PorcentajeRecargoZonaPeligrosa")
                        .HasColumnType("double precision");

                    b.Property<double>("PrecioPorKg")
                        .HasColumnType("double precision");

                    b.Property<double>("PrecioPorKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesTarifa", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.ConsentimientoOjoPatron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AceptadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("VersionTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConsentimientosOjoPatron", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.EmailNotificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CodigoSeguimiento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DestinatarioEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("EnviadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("Evento")
                        .HasColumnType("integer");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PaqueteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("Estado");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("SucursalId");

                    b.ToTable("EmailNotificaciones", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodigoCambioPendiente")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CodigoEmitidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosCodigoFallidos")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteCuentas")
                        .HasColumnType("integer");

                    b.Property<int?>("LimiteDestinoPendiente")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<int?>("PlanDestinoPendiente")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.GerenteProvincia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GerenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GerentesProvincias", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.HistorialEstadoEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("PaqueteId");

                    b.ToTable("HistorialEstadosEnvio", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.Incidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ChatFinalizado")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoSeguimiento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistorialEstadosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacionesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("PaqueteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParadasAfectadasJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RepartidorNombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SlaVenceEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TipoLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("FechaReporte");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Incidencias", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Accion")
                        .HasColumnType("integer");

                    b.Property<string>("Contexto")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecursoId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("UsuarioRol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Accion");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.MensajeIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("De")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidenciaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LeidoPorRepartidor")
                        .HasColumnType("boolean");

                    b.Property<bool>("LeidoPorSupervisor")
                        .HasColumnType("boolean");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MensajesIncidencia", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.OverrideOjoPatron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComentarioSupervisor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("Momento")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResueltoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SolicitadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("SolicitadoEn");

                    b.HasIndex("SupervisorId");

                    b.ToTable("OverridesOjoPatron", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.Paquete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Altura")
                        .HasColumnType("double precision");

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision");

                    b.Property<string>("CodigoSeguimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CostoEnvio")
                        .HasColumnType("double precision");

                    b.Property<double>("CostoRecargoSeguridad")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DiasEstimadosEntrega")
                        .HasColumnType("integer");

                    b.Property<float>("Distancia")
                        .HasColumnType("real");

                    b.Property<bool>("EsEnvioADomicilio")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsZonaPeligrosa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaCalendarizada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEstimadaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<float>("Prioridad")
                        .HasColumnType("real");

                    b.Property<string>("ProvinciaDestino")
                        .HasColumnType("text");

                    b.Property<Guid?>("PuntoPickUpId")
                        .HasColumnType("uuid");

                    b.Property<string>("RazonCancelacion")
                        .HasColumnType("text");

                    b.Property<string>("RazonDemora")
                        .HasColumnType("text");

                    b.Property<Guid?>("RepartidorAsignadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RutaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoEnvio")
                        .HasColumnType("integer");

                    b.Property<int>("TipoPaquete")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UbicacionActualActualizadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RutaId");

                    b.ToTable("Paquetes", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.PruebaOjoPatron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AlertnessScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<int>("Momento")
                        .HasColumnType("integer");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.Property<double>("ScoreAng")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreHap")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreNeu")
                        .HasColumnType("double precision");

                    b.Property<double>("ScoreSad")
                        .HasColumnType("double precision");

                    b.Property<double>("UmbralUsado")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PruebasOjoPatron", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.PuntoPickUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Horarios")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Provincia");

                    b.ToTable("PuntosPickUp", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinalizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IniciadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazonCancelacion")
                        .HasColumnType("text");

                    b.Property<Guid>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<double?>("UbicacionActualLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("UbicacionActualLng")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UbicacionActualizadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Rutas", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.SolicitudComercial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PlanInteres")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("Email");

                    b.ToTable("SolicitudesComerciales", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("ProvinciasCubiertas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sucursales", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Back.Domain.Models.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapacidadCarga")
                        .HasColumnType("double precision");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.ZonaPeligrosa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LatMax")
                        .HasColumnType("double precision");

                    b.Property<double>("LatMin")
                        .HasColumnType("double precision");

                    b.Property<double>("LngMax")
                        .HasColumnType("double precision");

                    b.Property<double>("LngMin")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZonasPeligrosas", (string)null);
                });

            modelBuilder.Entity("Back.Domain.Models.Administrador", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Back.Domain.Models.Gerente", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Gerente");
                });

            modelBuilder.Entity("Back.Domain.Models.Operador", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.HasDiscriminator().HasValue("Operador");
                });

            modelBuilder.Entity("Back.Domain.Models.Repartidor", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoJornada")
                        .HasColumnType("integer");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Repartidor");
                });

            modelBuilder.Entity("Back.Domain.Models.Supervisor", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("Back.Domain.Models.UsuarioPortal", b =>
                {
                    b.HasBaseType("Back.Domain.Models.Usuario");

                    b.HasDiscriminator().HasValue("UsuarioPortal");
                });

            modelBuilder.Entity("Back.Domain.Models.Paquete", b =>
                {
                    b.HasOne("Back.Domain.Models.Ruta", null)
                        .WithMany("Paquetes")
                        .HasForeignKey("RutaId");

                    b.OwnsOne("Back.Domain.Models.Cliente", "Destinatario", b1 =>
                        {
                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Destinatario_Apellido");

                            b1.Property<string>("Email")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("Destinatario_Email");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Destinatario_Nombre");

                            b1.Property<string>("Telefono")
                                .HasColumnType("text")
                                .HasColumnName("Destinatario_Telefono");

                            b1.HasKey("PaqueteId");

                            b1.ToTable("Paquetes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaqueteId");

                            b1.OwnsOne("Back.Domain.Models.Direccion", "Direccion", b2 =>
                                {
                                    b2.Property<Guid>("ClientePaqueteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("CP")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Calle")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Ciudad")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Provincia")
                                        .HasColumnType("text");

                                    b2.Property<string>("Referencia")
                                        .HasColumnType("text");

                                    b2.HasKey("ClientePaqueteId");

                                    b2.ToTable("Paquetes", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ClientePaqueteId");

                                    b2.OwnsOne("Back.Domain.Models.Ubicacion", "Ubicacion", b3 =>
                                        {
                                            b3.Property<Guid>("DireccionClientePaqueteId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Destinatario_Ubicacion_Latitud");

                                            b3.Property<double>("Longitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Destinatario_Ubicacion_Longitud");

                                            b3.HasKey("DireccionClientePaqueteId");

                                            b3.ToTable("Paquetes", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DireccionClientePaqueteId");
                                        });

                                    b2.Navigation("Ubicacion");
                                });

                            b1.Navigation("Direccion")
                                .IsRequired();
                        });

                    b.OwnsOne("Back.Domain.Models.Cliente", "Remitente", b1 =>
                        {
                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Remitente_Apellido");

                            b1.Property<string>("Email")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("Remitente_Email");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Remitente_Nombre");

                            b1.Property<string>("Telefono")
                                .HasColumnType("text")
                                .HasColumnName("Remitente_Telefono");

                            b1.HasKey("PaqueteId");

                            b1.ToTable("Paquetes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaqueteId");

                            b1.OwnsOne("Back.Domain.Models.Direccion", "Direccion", b2 =>
                                {
                                    b2.Property<Guid>("ClientePaqueteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("CP")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Calle")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Ciudad")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Provincia")
                                        .HasColumnType("text");

                                    b2.Property<string>("Referencia")
                                        .HasColumnType("text");

                                    b2.HasKey("ClientePaqueteId");

                                    b2.ToTable("Paquetes", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ClientePaqueteId");

                                    b2.OwnsOne("Back.Domain.Models.Ubicacion", "Ubicacion", b3 =>
                                        {
                                            b3.Property<Guid>("DireccionClientePaqueteId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Remitente_Ubicacion_Latitud");

                                            b3.Property<double>("Longitud")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Remitente_Ubicacion_Longitud");

                                            b3.HasKey("DireccionClientePaqueteId");

                                            b3.ToTable("Paquetes", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("DireccionClientePaqueteId");
                                        });

                                    b2.Navigation("Ubicacion");
                                });

                            b1.Navigation("Direccion")
                                .IsRequired();
                        });

                    b.OwnsOne("Back.Domain.Models.Ubicacion", "UbicacionActual", b1 =>
                        {
                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitud")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitud")
                                .HasColumnType("double precision");

                            b1.HasKey("PaqueteId");

                            b1.ToTable("Paquetes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaqueteId");
                        });

                    b.Navigation("Destinatario")
                        .IsRequired();

                    b.Navigation("Remitente")
                        .IsRequired();

                    b.Navigation("UbicacionActual");
                });

            modelBuilder.Entity("Back.Domain.Models.Ruta", b =>
                {
                    b.HasOne("Back.Domain.Models.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Back.Domain.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Back.Domain.Models.Ruta", b =>
                {
                    b.Navigation("Paquetes");
                });
#pragma warning restore 612, 618
        }
    }
}
