services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: logitrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kjkszpj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logitrack"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=logitrack;Username=postgres;Password=kjkszpj;SSL Mode=Disable
      - ASPNETCORE_ENVIRONMENT=Development
      - EnableDatabaseSeeder=true
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
